from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from io import BytesIO
from datetime import datetime
from typing import Dict, Any


class PDFService:
    @staticmethod
    def generate_report_pdf(
        title: str,
        report_type: str,
        input_payload: Dict[str, Any],
        output_summary: str,
        created_at: datetime
    ) -> bytes:
        """
        Generate PDF report from data
        
        Args:
            title: Report title
            report_type: Type of report
            input_payload: Input data
            output_summary: Summary text
            created_at: Report creation timestamp
            
        Returns:
            PDF file as bytes
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        story = []
        styles = getSampleStyleSheet()
        
        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#8b5cf6'),
            spaceAfter=30
        )
        story.append(Paragraph(title or "AegisAI Trust Report", title_style))
        story.append(Spacer(1, 0.2 * inch))
        
        # Metadata table
        metadata = [
            ['Report Type:', report_type.upper()],
            ['Generated:', created_at.strftime('%Y-%m-%d %H:%M:%S UTC')],
            ['Status:', 'COMPLETED']
        ]
        
        t = Table(metadata, colWidths=[2*inch, 4*inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f3f4f6')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey)
        ]))
        story.append(t)
        story.append(Spacer(1, 0.3 * inch))
        
        # Summary section
        story.append(Paragraph("<b>Executive Summary</b>", styles['Heading2']))
        story.append(Spacer(1, 0.1 * inch))
        story.append(Paragraph(output_summary or "No summary available.", styles['BodyText']))
        story.append(Spacer(1, 0.3 * inch))
        
        # Input payload section
        if input_payload:
            story.append(Paragraph("<b>Input Data</b>", styles['Heading2']))
            story.append(Spacer(1, 0.1 * inch))
            for key, value in input_payload.items():
                story.append(Paragraph(f"<b>{key}:</b> {value}", styles['BodyText']))
            story.append(Spacer(1, 0.2 * inch))
        
        # Footer
        story.append(Spacer(1, 0.5 * inch))
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=8,
            textColor=colors.grey
        )
        story.append(Paragraph(
            "Generated by AegisAI Enterprise Platform | Confidential",
            footer_style
        ))
        
        # Build PDF
        doc.build(story)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        return pdf_bytes
